title: Create an open source program
tagline: Leverage and contribute to open source software on behalf of your organization by creating an open source program.
description: Learn how to work alongside the open source communities that build software you're already using, and put your business at the forefront of the world's most innovative and secure code.
template:
  name: oss-enterprise
  repo: open-source-kit
before:
- type: createIssue
  title: Open source assessment
  body: welcome.md
  comments:
    - 01-goals-issue.md
tags:
  - Open source
  - Enterprise
  - Licensing
  - Templates
  - Guidelines

# Course artifacts:
# 1. Issue: Open source assessment
# 2. PR: Add a README
# 3. PR: Add contributing guidelines
# 4. Issue: Choose your code of conduct
# 5. PR: Create CODE_OF_CONDUCT.md
# 5. PR: Add communication guidelines
# 6. PR: Add checklists for issue template
# 7. PR: Maintainer guide
# 8. PR: License policy
# 9. PR: Add issue template for consuming OSS
# 10. PR: Add a template README
# 11. Issue: Congratulations

steps:

#1
- title: Establish preliminary goals
  description: Begin thinking about the goals of your open source program.
  link: '{{ repoUrl }}/issues/1'
  event: issue_comment.created
  actions:
  - type: createPullRequest
    title: Add a README
    body: 02-readme-pr.md
    head: main-readme
    action_id: readmePR
  - type: respond
    with: goto-readme-pr.md
    data:
      url: '%actions.readmePR.data.html_url%'
  - type: closeIssue
    issue: Open source assessment
    required: false

#2
- title: Give your repository a README.
  description: Merge the open source kit's README.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: createPullRequest
    title: Add contributing guidelines
    body: 03-contributing-pr.md
    head: contrib-guide
    action_id: contributingPR
  - type: respond
    with: goto-contributing-pr.md
    data:
      url: '%actions.contributingPR.data.html_url%'

#3
- title: Give your kit contributing guidelines
  description: Merge the open source kit's contributing guidelines.
  link: '{{ repoUrl }}/pull/3'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: createIssue
    title: Choose your code of conduct
    body: 04-code-of-conduct.md
    action_id: cocPR
  - type: respond
    with: goto-cocPr-pr.md
    data:
      url: '%actions.cocPR.data.html_url%'

# TODO: consider adding activity on compliant/violating COC behavior?

#4
- title: Provide a code of conduct
  description: Merge the pull request with your code of conduct.
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: 'Create CODE_OF_CONDUCT.md'
    else:
    - type: respond
      with: unknown-pr.md
      data:
        expected: 'Create CODE_OF_CONDUCT.md'
  - type: closeIssue
    issue: Choose your code of conduct
    required: false
  - type: createPullRequest
    title: Add communication guidelines
    body: 05-comm-guidelines-pr.md
    head: comms-strategy
    action_id: commPR
  - type: respond
    with: goto-comms-pr.md
    data:
      url: '%actions.commPR.data.html_url%'

#5
- title: Add communication guidelines
  description: Merge the pull request that adds communication guidelines for your organization.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add communication guidelines
  - type: createPullRequest
    title: Add checklists for issue template
    body: 06-checklists-pr.md
    head: using-oss
    action_id: checklistsPR
  - type: respond
    with: goto-checklists-pr.md
    data:
      url: '%actions.checklistsPR.data.html_url%'

#6
- title: Add checklists
  description: Provide checklists that can be used to release a new open source project.
  link: '{{ repoUrl }}/pull/7'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createPullRequest
    title: Maintainer guide
    body: 07-maintainer-pr.md
    head: maintainer-guide
    action_id: maintainerPR
  - type: respond
    with: goto-maintainer-pr.md
    data:
      url: '%actions.maintainerPR.data.html_url%'

#7
- title: Add a maintainer's guide
  description: Merge the pull request that creates a guide for open source maintainers.
  link: '{{ repoUrl }}/pull/8'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
  - type: createPullRequest
    title: License policy
    body: 08-license-policy-pr.md
    head: license-policy
    action_id: licensePR
  - type: respond
    with: goto-license-pr.md
    data:
      url: '%actions.licensePR.data.html_url%'

# TODO: consider a licensing quiz or activity

#8
- title: Add a license policy
  description: Help your organization determine what licenses should be used by creating a license policy.
  link: '{{ repoUrl }}/pull/9'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: createPullRequest
    title: Add issue template for consuming OSS
    body: 09-consuming-pr.md
    head: key-questions
    action_id: consumingPR
  - type: respond
    with: goto-consuming-pr.md
    data:
      url: '%actions.consumingPR.data.html_url%'

#9
- title: Provide guidance for consuming open source software
  description: Merge the pull request that adds guidance for consuming open source software within your organization.
  link: '{{ repoUrl }}/pull/10'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: createPullRequest
    title: Add a template README
    body: 10-template-readme-pr.md 
    head: template-readme
    action_id: templateReadme
  - type: respond
    with: goto-template-readme-pr.md
    data:
      url: '%actions.templateReadme.data.html_url%'

#10
- title: Add a template README
  description: Provide a README that team members can use when open sourcing their projects.
  link: '{{ repoUrl }}/pull/11'
  event: pull_request.closed
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
    - type: respond
      with: e-unexpected-merge.md
  - type: createIssue
    title: Congratulations
    body: done.md
    action_id: finalIssue
    data:
      forkURL: '%payload.repository.html_url%/fork'
      downloadURL: '%payload.repository.html_url%/archive/master.zip'
  - type: respond
    with: goto-final-issue.md
    data:
      url: '%actions.finalIssue.data.html_url%'