title: Open source in the enterprise
tagline: Open source in the enterprise
description: Open source in the enterprise
template:
  name: oss-enterprise
  repo: false
before:
- type: createIssue
  title: Maturity assessment
  body: welcome.md
  comments:
    - 01-goals-issue.md
- type: updateBranchProtection

# Course artifacts:
# 1. Issue: Maturity assessment
# 2. PR: Add a README
# 3. PR: Add contributing guidelines
# 4. PR: Add a code of conduct
# 5. PR: Add communication guidelines
# 6. PR: Add checklists for issue template
# 7. PR: Maintainer guide
# 8. PR: License policy

# Rough outline:
# - Purpose: create an open source releases-like repo, a resource used by your organization to launch open source projects. 
#   This could include:
#   - purpose of open source program
#   - first steps in releasing open source software
#   - code of conduct
#   - relation to business goals
# - Step 1: Add some template files
#   - in a PR, learner adds CONTRIBUTING.md file
#   - perhaps merge in multiple contributing guidelines
# - Step 2: Learner merges in COC
#   - quiz on compliant/violating COC behavior?
# - Step 3: Learner merges in communication guidelines
# - Step 4: Learner merges an open source checklist
#   - define a process for OSS
#   - it's self serve
# - Step 5: Learner merges in a maintainer guide
# - Step 6: Learner merges in license requirements
#   - activity: pick the right license
# - Step 7: Learner adds issue templates that can be copied
# - Step 8: Learner adds in README template that can be copied
# - Step 9: 

steps:

#1
- title: Establish preliminary goals
  description: Begin thinking about the goals of your open source program.
  link: '{{ repoUrl }}/issues/1'
  event: issue_comment.created
  actions:
  # TODO: template repo needs a `add-readme` branch
  - type: createPullRequest
    title: Add a README
    body: 02-readme-pr.md
    head: add-readme
    action_id: readmePR
  - type: respond
    with: goto-readme-pr.md
    data:
      url: '%actions.readmePR.data.html_url%'

#2
- title: Give your repository a README.
  description: Approve the open source kit's README.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-contributing` branch
  - type: createPullRequest
    title: Add contributing guidelines
    body: 03-contributing-pr.md
    head: add-contributing
    action_id: contributingPR
  - type: respond
    with: goto-contributing-pr.md
    data:
      url: '%actions.contributingPR.data.html_url%'

#3
- title: Give your kit contributing guidelines
  description: Approve the opens ource kit's contributing guidelines.
  link: '{{ repoUrl }}/pull/3'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-coc` branch
  - type: createPullRequest
    title: Add a code of conduct
    body: 04-code-of-conduct-pr.md
    head: add-coc
    action_id: cocPR
  - type: respond
    with: goto-cocPr-pr.md
    data:
      url: '%actions.cocPR.data.html_url%'

# TODO: consider adding activity on compliant/violating COC behavior?

#4
- title: Provide a code of conduct
  description: Approve the pull request adding a code of conduct template
  link: '{{ repoUrl }}/pull/4'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-comm-guidelines` branch
  - type: createPullRequest
    title: Add communication guidelines
    body: 05-comm-guidelines-pr.md
    head: add-comm-guidelines
    action_id: commPR
  - type: respond
    with: goto-compr-pr.md
    data:
      url: '%actions.commPR.data.html_url%'

#5
- title: Add communication guidelines
  description: Approve the pull request that adds communication guidelines for your organization.
  link: '{{ repoUrl }}/pull/5'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-checklists` branch
  - type: createPullRequest
    title: Add checklists for issue template
    body: 06-checklists-pr.md
    head: add-checklists
    action_id: checklistsPR
  - type: respond
    with: goto-checklists-pr.md
    data:
      url: '%actions.checklistsPR.data.html_url%'

#6
- title: Add checklists
  description: Provide checklists that can be used to release a new open source project.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-maintainer-guide` branch
  - type: createPullRequest
    title: Maintainer guide
    body: 07-maintainer-pr.md
    head: add-maintainer-guide
    action_id: maintainerPR
  - type: respond
    with: goto-maintainer-pr.md
    data:
      url: '%actions.maintainerPR.data.html_url%'

#7
- title: Add a maintainer's guide
  description: Approve the PR that gives open source maintainers some guidance with a guide.
  link: '{{ repoUrl }}/pull/7'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-license` branch
  - type: createPullRequest
    title: License policy
    body: 08-license-policy-pr.md
    head: add-license
    action_id: licensePR
  - type: respond
    with: goto-license-pr.md
    data:
      url: '%actions.licensePR.data.html_url%'

# TODO: consider a licensing quiz or activity

#7
- title: Add a license policy
  description: Help your organization determine what licenses should be used by creating a license policy.
  link: '{{ repoUrl }}/pull/8'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
