title: Open source in the enterprise
tagline: Open source in the enterprise
description: Open source in the enterprise
template:
  name: oss-enterprise
  repo: false
before:
- type: createIssue
  title: Maturity assessment
  body: welcome.md
  comments:
    - 01-goals-issue.md
- type: updateBranchProtection

# Course artifacts:
# - Purpose: create an open source releases-like repo, a resource used by your organization to launch open source projects. 
#   This could include:
#   - purpose of open source program
#   - first steps in releasing open source software
#   - code of conduct
#   - relation to business goals
# - Step 1: Add some template files
#   - in a PR, learner adds CONTRIBUTING.md file
#   - perhaps merge in multiple contributing guidelines
# - Step 2: Learner merges in COC
#   - quiz on compliant/violating COC behavior?
# - Step 3: Learner merges in communication guidelines
# - Step 4: Learner merges an open source checklist
#   - define a process for OSS
#   - it's self serve
# - Step 5: Learner merges in a maintainer guide
# - Step 6: Learner merges in license requirements
#   - activity: pick the right license
# - Step 7: Learner adds issue templates that can be copied
# - Step 8: Learner adds in README template that can be copied
# - Step 9: 

steps:

#1
- title: Establish preliminary goals
  description: Begin thinking about the goals of your open source program.
  link: '{{ repoUrl }}/issues/1'
  event: issue_comment.created
  actions:
  # TODO: template repo needs a `add-readme` branch
  - type: createPullRequest
    title: Add a README
    body: 02-readme-pr.md
    head: add-readme
    action_id: readmePR
  - type: respond
    with: goto-readme-pr.md
    data:
      url: '%actions.readmePR.data.html_url%'

- title: Give your repository a README.
  description: Approve the open source kit's README.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-contributing` branch
  - type: createPullRequest
    title: Add contributing guidelines
    body: 03-contributing-pr.md
    head: add-contributing
    action_id: contributingPR
  - type: respond
    with: goto-contributing-pr.md
    data:
      url: '%actions.contributingPR.data.html_url%'

- title: Give your kit contributing guidelines
  description: Approve the opens ource kit's contributing guidelines.
  link: '{{ repoUrl }}/pull/3'
  event: pull_request_review.submitted
  actions:
  - type: gate
    left: '%payload.review.state%'
    operator: ===
    right: approved
  # TODO: template repo needs a `add-coc` branch
  - type: createPullRequest
    title: Add a code of conduct
    body: 04-code-of-conduct-pr.md
    head: add-coc
    action_id: cocPr
  - type: respond
    with: goto-cocPr-pr.md
    data:
      url: '%actions.cocPr.data.html_url%'
